# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Pull request

on:
  pull_request:

env:
  TEST_TAG: sppnaut_sppnaut

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/*requirements.txt"

      - name: Python version
        run: python -V
      - name: Unit tests
        uses: ./.github/actions/unit-tests

      - name: Build docker image
        uses: ./.github/actions/build-docker-image
        with:
          test_tag: ${{ env.TEST_TAG }}

      - name: Integration test docker image
        uses: ./.github/actions/integration-test-docker-image
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
