# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Push to Main

on:
  push:
    branches:
      - main

#fixme : pass the env variable as input of the action : explicit relationship
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_ID: app_e77e446e-754a-433d-8f8f-fe339d699a75
  TEST_TAG: sppnaut_sppnaut

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/*requirements.txt"

      - name: Unit tests
        uses: ./.github/actions/unit-tests

      - name: Build docker image
        uses: ./.github/actions/build-docker-image
        with:
          test_tag: ${{ env.TEST_TAG }}

      - name: Integration test docker image
        uses: ./.github/actions/integration-test-docker-image
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push and deploy docker image
        uses: ./.github/actions/push-and-deploy-docker-image
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clever_token: ${{ secrets.CLEVER_TOKEN }}
          clever_secret: ${{ secrets.CLEVER_SECRET }}
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
          app_id: ${{ env.APP_ID }}
